import Mathlib.Topology.Sheaves.Stalks
import Mathlib.Topology.LocalHomeomorph
import Mathlib.Topology.Basic


/-!
# Étale Space Skeleton for a Sheaf `F` on a Space `X`


This file provides the *definitions and structure* needed to build the étale
space of a sheaf. Long proofs are omitted and replaced with `sorry`.
-/


open Topology CategoryTheory Opposite


universe u v


variable {X : Type u} [TopologicalSpace X]


namespace EtaleSpace


/-- The underlying type of the étalé space: the disjoint union of all stalks. -/
@[simp]
structure EtaleSpace (F : Sheaf (Type v) X) where
point : X
germ : F.stalk point


/-- Projection map `E → X`. -/
def proj {F : Sheaf (Type v) X} : EtaleSpace F → X :=
fun e => e.point


/-- Basic open sets of the étale topology. -/
def basicOpen (F : Sheaf (Type v) X)
(U : Opens X) (s : F.obj (op U)) : Set (EtaleSpace F) :=
{ e | e.point ∈ U ∧ F.germ e.point s = e.germ }


/-- The set of all basic opens (as a basis). -/
def basisSets (F : Sheaf (Type v) X) : Set (Set (EtaleSpace F)) :=
{ V | ∃ (U : Opens X) (s : F.obj (op U)), V = basicOpen F U s }


/-- The topology on the étale space generated by basic opens. -/
instance etaleTopology (F : Sheaf (Type v) X) : TopologicalSpace (EtaleSpace F) :=
TopologicalSpace.generateFrom (basisSets F)


/-- The projection map is continuous. -/
theorem proj_continuous (F : Sheaf (Type v) X) : Continuous (proj (F := F)) := by
-- proof uses basis characterization
sorry


/-- A chart around an étale point giving a local homeomorphism. -/
def chartAt (F : Sheaf (Type v) X) (e : EtaleSpace F) :
LocalHomeomorph (EtaleSpace F) X :=
by
-- Construct from classical representation theorem of stalks
-- Forward map: proj
-- Inverse map: choose rep section around e
-- Need to show bijection + continuity
sorry


/-- The projection of the étale space is a local homeomorphism. -/
theorem proj_isLocalHomeomorph (F : Sheaf (Type v) X) :
∀ x, ∃ H : LocalHomeomorph (EtaleSpace F) X,
H.toFun = proj ∧ H.source ∋ x :=
by
intro e
refine ⟨chartAt F e, ?_, ?_⟩
· -- H.toFun = proj
sorry
· -- e ∈ H.source
sorry


/-- Define the sheaf of sections of the étale projection. -/
def sectionPresheaf (F : Sheaf (Type v) X) : Presheaf (Type v) X :=
by
-- On an open U: continuous sections of proj over U
-- This appears in mathlib as `LocalHomeomorph`.sections
sorry


/-- Prove this presheaf is a sheaf. -/
def sectionSheaf (F : Sheaf (Type v) X) : Sheaf (Type v) X :=
by
-- Use existing mathlib machinery for sheafification or local homeomorphisms
sorry


end EtaleSpace
